import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Header from '@/components/Header'
import About from '@/components/About'
import Footer from '@/components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Carl Justin Gamos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Navbar */}
        <Navbar />

        {/* Header */}
        <Header />

        <div className='sm:w-[35rem] md:w-[38rem] lg:w-[40rem] m-auto'>
          {/* Body */}
          <About />

          {/* Footer */}
          <Footer />
        </div>

      </main>
    </>
  )
}
