import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Header from '@/components/Header'
import About from '@/components/About'
import Footer from '@/components/Footer'

import { motion } from "framer-motion"


export default function Home() {
  return (
    <>
      <Head>
        <title>Carl Justin Gamos - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>


        {/* Body */}
        <div className='sm:w-[35rem] md:w-[38rem] lg:w-[40rem] m-auto'>

          <motion.div
            initial={{ y: 100, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ type: "spring", stiffness: 30 }}
          >
            {/* Header */}
            <Header />
          </motion.div>

          <motion.div
            initial={{ y: 100, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.3, type: "spring", stiffness: 30 }}
          >
            {/* About */}
            <About />
          </motion.div>

        </div>

      </main>
    </>
  )
}
